//import dataApi from './apis/apiBase';
//import apiLowCode from './apis/apiLowcode';
import apiEsi from "./apis/apiEsi";

export const getMyTickets = async () => {
  //const { data } = await dataApi.get('v1/ticket/my-tickets');
  //const { data } = await dataApi.get('servicerequestincident/search');
  //const { data } = await apiLowCode.get('a5x/user');
  /*
  const payload = {
    requesterId: 17,
    sessionID: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJRZ2s2Z3VXNFBnZ2dzc093SGp2YVp4ZjRHWVd3YzYyczNaSWN1ZGdBWTZZIn0.eyJleHAiOjE3NTI1MjE0MjYsImlhdCI6MTc1MjUyMTEyNiwiYXV0aF90aW1lIjoxNzUyNTE5MjY0LCJqdGkiOiI0YjJjYTE2MC04ZDZhLTQ5OWEtYjQ1ZS03ODc2MmFmMDlkNWQiLCJpc3MiOiJodHRwczovL2tleWNsb2FrLjRiaXoub25lL2F1dGgvcmVhbG1zL2E1eC1kZXYiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiOWY5ODI5MjYtOTIxMi00YTYwLTk5N2UtZWU2MTMzNjkzOGMyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZnJvbnQtbWFuYWdlciIsIm5vbmNlIjoiYjJlZjhhNzQtNGUzZi00MmY0LWIxN2QtMzc2ZjI3ZGFjOTcyIiwic2Vzc2lvbl9zdGF0ZSI6Ijk2NDVlZjU1LTAxOWUtNDViNi1hODVlLWQzZmJmZjY0MjBkYSIsImFjciI6IjAiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiYWNlc3NfbG93Y29kZSIsImFjY2Vzc19pdHNtIiwiYWNjZXNzX2V2ZW50cyIsImtibl91c2VyIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtYTV4LWRldiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJoeXBlcl9jbGllbnQiOiI3OWQ3MTc5OC04NDVmLTRmMzUtYWQ3NS0xNTg2OTE0NzRhZTQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJHdWlsaGVybWUgVmFsZXJpYW5vIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZ3VpbGhlcm1lLnZhbGVyaWFubyIsImdpdmVuX25hbWUiOiJHdWlsaGVybWUiLCJmYW1pbHlfbmFtZSI6IlZhbGVyaWFubyIsImVtYWlsIjoiZ3VpbGhlcm1lLnZhbGVyaWFub0BzZXZlbnJlZC5jb20uYnIiLCJoeXBlcl9jbHVzdGVyX3NwYWNlIjoiZWIxODlkN2UtMjhmZi00MzcwLTlhZmQtOTMzMzU1ZjQyMTAzIn0.Ekh_0Da3fOkMhb4v_p-6Kc_5hwn4Rir-WpvnqWsEt_Nc6TnNQtjOZh3-bIS9-2Jiea9lV04OlTi6ZvvyiIQbd92afYAanFKwlCEbQAdZn7U2lTCltx0_fy8svFI54uIL16VpnsL3SAwM1MBvWfgZz7gClZn1ElnYkqy5oGn75oywF0ADjf2mO87wT3lW69Gh9WzLSt1DBHxi0uTA9GXcJ8eE6fWBEl8qIO5lHpTvsZU9VbNK6JTeWBYcV4zijulzJDFvlCJHtWF37YZOEbDciFwszU-elnCtHB1jV1ICdxD6WuoeYkSHcsF6uH0HZWJgwe4yxMbdwjF-MpD_wTzWgA",
    serviceRequestId: 238
  }
  const { data } = await dataApi.post('servicerequestincident/search', payload);*/
  const payload = {
  
  }

  const { data } = await apiEsi.post('meusChamados/flows', payload);
  return data;
};